# Generated by Django 5.0.3 on 2024-04-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_delete_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(auto_created=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
